export class DependencyPinner {
  // The absolute source of truth for versions
  private static readonly KNOWN_GOOD_VERSIONS: Record<string, string> = {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^5.2.2",
    "vite": "^5.0.0",
    "tailwindcss": "^3.4.0",
    "lucide-react": "^0.344.0",
    "framer-motion": "^11.0.0"
  };

  /**
   * Takes a raw package.json string (generated by LLM) and forces the dependencies
   * to match our known-good versions, preventing version mismatch crashes.
   */
  static pin(rawPackageJson: string): string {
    try {
      const pkg = JSON.parse(rawPackageJson);
      
      if (pkg.dependencies) {
        for (const dep in pkg.dependencies) {
          if (this.KNOWN_GOOD_VERSIONS[dep]) {
            pkg.dependencies[dep] = this.KNOWN_GOOD_VERSIONS[dep];
          }
        }
      }
      
      if (pkg.devDependencies) {
        for (const dep in pkg.devDependencies) {
          if (this.KNOWN_GOOD_VERSIONS[dep]) {
            pkg.devDependencies[dep] = this.KNOWN_GOOD_VERSIONS[dep];
          }
        }
      }
      
      console.log(`[DependencyPinner] Locked dependency versions to Known-Good Dictionary.`);
      return JSON.stringify(pkg, null, 2);
    } catch (error) {
      console.warn(`[DependencyPinner] Failed to parse package.json, bypassing...`);
      return rawPackageJson;
    }
  }
}
