import { prisma } from '@/src/lib/prisma';
import { CostTracker } from '@/src/services/cost-tracker';
import { LearningStore } from '@/src/services/learning-store';
import { TraceLogger } from '@/src/services/trace-logger';

/**
 * SCRIBE Agent — auto-documentation after each phase and at pipeline completion.
 * Generates and persists: AI Dev Log, Cost Log, Issues Tracker.
 * Stored as ProjectFile entries so they appear in the project output.
 */
export class ScribeAgent {
  /**
   * Generate documentation after a phase completes.
   * Called by DAGExecutor.approveNode() after phase-executor approval.
   */
  static async documentPhase(
    runId: string,
    phaseIndex: number,
    stageId: string,
    stageName: string,
    durationMs: number | null
  ): Promise<void> {
    const run = await prisma.pipelineRun.findUnique({
      where: { id: runId },
      select: { projectId: true, traceId: true, userInput: true },
    });
    if (!run) return;

    const traceId = run.traceId || 'unknown';
    const spanId = TraceLogger.generateSpanId();

    try {
      // Get stage cost info
      const stage = await prisma.pipelineStage.findUnique({
        where: { id: stageId },
        select: { inputTokens: true, outputTokens: true, costUsd: true, modelUsed: true, retryCount: true, durationMs: true },
      });

      const timestamp = new Date().toISOString();
      const costUsd = stage?.costUsd || 0;
      const inputTokens = stage?.inputTokens || 0;
      const outputTokens = stage?.outputTokens || 0;
      const model = stage?.modelUsed || 'unknown';
      const retries = stage?.retryCount || 0;

      // --- AI Dev Log ---
      const devLogPath = 'AI_DEV_LOG.md';
      const existingDevLog = await prisma.projectFile.findFirst({
        where: { projectId: run.projectId, filePath: devLogPath, runId: null },
        select: { content: true },
      });

      const devLogEntry = `\n### Phase ${phaseIndex}: ${stageName}\n` +
        `- **Timestamp:** ${timestamp}\n` +
        `- **Duration:** ${durationMs ? `${(durationMs / 1000).toFixed(1)}s` : 'N/A'}\n` +
        `- **Model:** ${model}\n` +
        `- **Tokens:** ${inputTokens.toLocaleString()} in / ${outputTokens.toLocaleString()} out\n` +
        `- **Cost:** $${costUsd.toFixed(4)}\n` +
        `- **Retries:** ${retries}\n` +
        `- **Status:** Approved\n`;

      const devLogContent = existingDevLog?.content
        ? existingDevLog.content + devLogEntry
        : `# AI Dev Log\n\nAutomatically generated by Scribe agent.\n\n---\n${devLogEntry}`;

      await prisma.projectFile.upsert({
        where: { projectId_filePath: { projectId: run.projectId, filePath: devLogPath } },
        create: { projectId: run.projectId, filePath: devLogPath, content: devLogContent, language: 'markdown' },
        update: { content: devLogContent },
      });

      // --- Cost Log ---
      const costLogPath = 'AI_COST_LOG.md';
      const existingCostLog = await prisma.projectFile.findFirst({
        where: { projectId: run.projectId, filePath: costLogPath, runId: null },
        select: { content: true },
      });

      const costLogEntry = `| Phase ${phaseIndex} | ${stageName} | ${model} | ${inputTokens.toLocaleString()} | ${outputTokens.toLocaleString()} | $${costUsd.toFixed(4)} | ${retries} | ${timestamp} |\n`;

      const costLogContent = existingCostLog?.content
        ? existingCostLog.content + costLogEntry
        : `# AI Cost Log\n\nAutomatically generated by Scribe agent.\n\n| Phase | Stage | Model | Input Tokens | Output Tokens | Cost | Retries | Timestamp |\n|-------|-------|-------|-------------|--------------|------|---------|----------|\n${costLogEntry}`;

      await prisma.projectFile.upsert({
        where: { projectId_filePath: { projectId: run.projectId, filePath: costLogPath } },
        create: { projectId: run.projectId, filePath: costLogPath, content: costLogContent, language: 'markdown' },
        update: { content: costLogContent },
      });

      // --- Issues Tracker (from learning store) ---
      const patterns = await LearningStore.getWarningsFor(stageName);
      if (patterns.length > 0) {
        const issuesPath = 'ISSUES_TRACKER.md';
        const existingIssues = await prisma.projectFile.findFirst({
          where: { projectId: run.projectId, filePath: issuesPath, runId: null },
          select: { content: true },
        });

        const issueEntries = patterns.map((p) => `- ${p}`).join('\n');
        const issueBlock = `\n### Phase ${phaseIndex} Issues (${timestamp})\n${issueEntries}\n`;

        const issuesContent = existingIssues?.content
          ? existingIssues.content + issueBlock
          : `# Issues Tracker\n\nAutomatically generated by Scribe agent. Issues detected during pipeline execution.\n\n---\n${issueBlock}`;

        await prisma.projectFile.upsert({
          where: { projectId_filePath: { projectId: run.projectId, filePath: issuesPath } },
          create: { projectId: run.projectId, filePath: issuesPath, content: issuesContent, language: 'markdown' },
          update: { content: issuesContent },
        });
      }

      await TraceLogger.log({
        runId,
        traceId,
        spanId,
        eventType: 'stage_complete',
        source: 'scribe',
        message: `Scribe documented Phase ${phaseIndex}: ${stageName}`,
        metadata: { phaseIndex, costUsd, inputTokens, outputTokens, retries },
      });

      console.log(`[Scribe] Documented Phase ${phaseIndex}: ${stageName} ($${costUsd.toFixed(4)}, ${retries} retries)`);

      // Auto-commit phase files to GitLab if project has a repo URL
      try {
        await ScribeAgent.commitPhaseToGitLab(runId, run.projectId, phaseIndex, stageName, {
          costUsd, inputTokens, outputTokens, model, retries,
        });
      } catch (gitErr) {
        console.error('[Scribe] GitLab commit failed (non-fatal):', gitErr);
      }
    } catch (err) {
      console.error('[Scribe] Documentation failed (non-fatal):', err);
    }
  }

  /**
   * Commit phase files to GitLab via API (no git clone needed).
   */
  private static async commitPhaseToGitLab(
    runId: string,
    projectId: string,
    phaseIndex: number,
    stageName: string,
    metadata: { costUsd: number; inputTokens: number; outputTokens: number; model: string; retries: number }
  ): Promise<void> {
    // Check if project has a repo URL stored in the latest forge run
    const forgeRun = await prisma.pipelineRun.findFirst({
      where: { projectId, type: 'build' },
      orderBy: { startedAt: 'desc' },
      select: { userInput: true },
    });
    // Extract repo URL from user input if it looks like a GitLab URL
    const repoMatch = forgeRun?.userInput?.match(/(https?:\/\/[^\s]+\.git)/);
    if (!repoMatch) return;
    const repoUrl = repoMatch[1];

    const project = await prisma.project.findUnique({
      where: { id: projectId },
      select: { userId: true, name: true },
    });
    if (!project) return;

    const account = await prisma.account.findFirst({
      where: { userId: project.userId, provider: 'gitlab' },
      select: { access_token: true },
    });
    if (!account?.access_token) return;

    const phaseFiles = await prisma.projectFile.findMany({
      where: { runId },
      select: { filePath: true, content: true },
    });
    if (phaseFiles.length === 0) return;

    const cleanUrl = repoUrl.replace(/\.git$/, '');
    const url = new URL(cleanUrl);
    const host = url.origin;
    const projectPath = url.pathname.slice(1);

    let Gitlab: typeof import('@gitbeaker/rest').Gitlab;
    try {
      const mod = await import('@gitbeaker/rest');
      Gitlab = mod.Gitlab;
    } catch {
      console.log('[Scribe] @gitbeaker/rest not available — skipping GitLab commit');
      return;
    }

    const gl = new Gitlab({ host, token: account.access_token });

    const actions = phaseFiles.map((f) => ({
      action: 'create' as const,
      filePath: f.filePath,
      content: f.content,
    }));

    const commitMessage = [
      `forge: Phase ${phaseIndex} — ${stageName}`,
      '',
      `Model: ${metadata.model}`,
      `Tokens: ${metadata.inputTokens.toLocaleString()} in / ${metadata.outputTokens.toLocaleString()} out`,
      `Cost: $${metadata.costUsd.toFixed(4)}`,
      `Retries: ${metadata.retries}`,
      `Run: ${runId}`,
    ].join('\n');

    try {
      const proj = await gl.Projects.show(projectPath);
      const branch = `forge/${project.name.toLowerCase().replace(/\s+/g, '-')}/${Date.now().toString(36)}`;
      await gl.Branches.create(projectPath, branch, proj.default_branch || 'main');
      await gl.Commits.create(projectPath, branch, commitMessage, actions);
      console.log(`[Scribe] Committed Phase ${phaseIndex} to GitLab branch ${branch} (${phaseFiles.length} files)`);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      console.error(`[Scribe] GitLab commit failed: ${message}`);
    }
  }

  /**
   * Generate a final summary at pipeline completion.
   * Called by DAGExecutor.advanceDAG() when runComplete=true.
   */
  static async documentRunCompletion(runId: string): Promise<void> {
    const run = await prisma.pipelineRun.findUnique({
      where: { id: runId },
      include: {
        stages: { orderBy: { stageIndex: 'asc' } },
      },
    });
    if (!run) return;

    try {
      const costSummary = await CostTracker.aggregateRunCost(runId);
      const totalCost = costSummary.totalCostUsd;
      const totalTokensIn = costSummary.totalInputTokens;
      const totalTokensOut = costSummary.totalOutputTokens;
      const totalDuration = run.totalDurationMs || 0;
      const stageCount = run.stages.length;
      const approvedCount = run.stages.filter((s) => s.status === 'approved').length;
      const retryCount = run.stages.reduce((sum, s) => sum + s.retryCount, 0);

      const timestamp = new Date().toISOString();

      // Append completion summary to dev log
      const devLogPath = 'AI_DEV_LOG.md';
      const existingDevLog = await prisma.projectFile.findFirst({
        where: { projectId: run.projectId, filePath: devLogPath, runId: null },
        select: { content: true },
      });

      const summaryEntry = `\n---\n\n## Run Summary (${timestamp})\n\n` +
        `- **Status:** ${run.status}\n` +
        `- **Total Duration:** ${(totalDuration / 1000).toFixed(1)}s\n` +
        `- **Stages:** ${approvedCount}/${stageCount} approved\n` +
        `- **Total Retries:** ${retryCount}\n` +
        `- **Total Tokens:** ${totalTokensIn.toLocaleString()} in / ${totalTokensOut.toLocaleString()} out\n` +
        `- **Total Cost:** $${totalCost.toFixed(4)}\n`;

      const devLogContent = existingDevLog?.content
        ? existingDevLog.content + summaryEntry
        : `# AI Dev Log\n\n${summaryEntry}`;

      await prisma.projectFile.upsert({
        where: { projectId_filePath: { projectId: run.projectId, filePath: devLogPath } },
        create: { projectId: run.projectId, filePath: devLogPath, content: devLogContent, language: 'markdown' },
        update: { content: devLogContent },
      });

      console.log(`[Scribe] Run completion summary written for ${runId} ($${totalCost.toFixed(4)}, ${retryCount} retries)`);
    } catch (err) {
      console.error('[Scribe] Run completion documentation failed (non-fatal):', err);
    }
  }
}
