export const dynamic = 'force-dynamic'

import { rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { NextResponse } from 'next/server'
import { getSessionOrDemo } from '@/src/lib/auth-helpers'
import { getForgeRunWithDetails, updateForgeRun, saveForgeRunResult } from '@/src/services/forge/db'
import { publishToGitLab, getGitLabToken } from '@/src/services/forge/utils/publish'

export async function POST(
  _req: Request,
  { params }: { params: { id: string } },
): Promise<NextResponse> {
  const session = await getSessionOrDemo()
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const runId = params.id

  try {
    const details = await getForgeRunWithDetails(runId)
    if (!details) {
      return NextResponse.json({ error: 'Run not found' }, { status: 404 })
    }

    const { run, diff } = details
    if (run.userId !== session.user.id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    if (run.status !== 'awaiting_approval' || run.stage !== 'code') {
      return NextResponse.json(
        { error: `Cannot publish: status="${run.status}" stage="${run.stage}". Use /advance for plan approval.` },
        { status: 409 },
      )
    }

    if (!diff) {
      return NextResponse.json({ error: 'No diff found for this run' }, { status: 409 })
    }

    await updateForgeRun(runId, { status: 'publishing' })

    const token = await getGitLabToken(session.user.id)
    const workDir = join(tmpdir(), `forge-${runId}`)

    const title = run.mode === 'build'
      ? (run.prdTitle ?? `forge: feature from run ${runId.slice(0, 8)}`)
      : `forge: fix from debug run ${runId.slice(0, 8)}`

    const description = run.mode === 'build'
      ? (run.prdSummary ?? '')
      : `Automated fix generated by Forge debug pipeline.\nRun ID: ${runId}`

    const result = await publishToGitLab({
      workDir,
      repoUrl: run.repoUrl,
      files: diff.files as Array<{ path: string; content: string }>,
      branchName: run.branchName ?? undefined,
      title,
      description,
      token,
    })

    await saveForgeRunResult(runId, result)
    await updateForgeRun(runId, {
      status: 'complete',
      completedAt: new Date().toISOString(),
      branchName: result.branch,
    })

    try {
      rmSync(workDir, { recursive: true, force: true })
    } catch {
      // Non-fatal cleanup
    }

    return NextResponse.json(result)
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Publish failed'
    await updateForgeRun(runId, { status: 'failed', error: message }).catch(() => {})
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
