/** Node types in the execution DAG */
export type DAGNodeType = 'agent' | 'skill' | 'verify' | 'gate';

/** Gate types for human approval nodes */
export type GateType = 'plan_approval' | 'phase_review' | 'final_review';

/** A node in the execution DAG */
export interface DAGNode {
  id: string;
  skillName: string | null;
  displayName: string;
  description: string;
  nodeType: DAGNodeType;
  dependsOn: string[];
  parallelGroup: string | null;
  gateType: GateType | null;
  maxRetries: number;
  /** Phase index this node belongs to (for multi-phase builds) */
  phaseIndex: number | null;
}

/** An edge in the execution DAG */
export interface DAGEdge {
  from: string;
  to: string;
  condition: string | null;
}

/** The full execution plan generated by the intake agent */
export interface ExecutionPlan {
  type: 'build' | 'diagnostic' | 'refactor';
  nodes: DAGNode[];
  edges: DAGEdge[];
  estimatedPhases: number;
  parallelGroups: string[];
}

/** Triage decisions when a node fails */
export type TriageDecision =
  | { action: 'retry'; nodeId: string; modifiedContext: string }
  | { action: 'reroute'; targetNodeId: string; reason: string }
  | { action: 'escalate'; reason: string };

/** Build verification result */
export interface VerifyResult {
  success: boolean;
  installOutput: string;
  buildOutput: string;
  errors: string[];
  warnings: string[];
  durationMs: number;
}

/** Project type detected from files on disk */
export type ProjectType = 'node' | 'python' | 'go' | 'static' | 'unknown';

/** Status of a node during DAG execution */
export type DAGNodeStatus =
  | 'pending'
  | 'blocked'      // waiting on dependencies
  | 'ready'        // dependencies met, queued for execution
  | 'running'
  | 'awaiting_approval'
  | 'approved'
  | 'failed'
  | 'retrying'
  | 'skipped';
